// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijyyspysltkgknzlaifw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqeXlzcHlzbHRrZ2tuemxhaWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDE5MTAsImV4cCI6MjA2OTM3NzkxMH0.OmQN0TDO_1lHpeBPVIhsw0s94FpTYKNEP7SQZ5Bkehs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});